name: bgg_flutter_client
description: "A lightweight Dart client for the BoardGameGeek XML API2."
version: 0.0.3
homepage: https://github.com/a-zhuravchak/bggapi
environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

repository: https://github.com/a-zhuravchak/bggapi
license: BSD-3-Clause

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  test: ^1.25.8

example:
  directory: example

flutter:


