name: bggapi
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  build_runner: ^2.4.6
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  mockito: ^5.4.5
  runner: ^1.0.0
  test: ^1.25.8
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


